//
// Created by Marcin on 29.03.2019.
//

#ifndef SERVER_CONSULTATIONSTATUS_H
#define SERVER_CONSULTATIONSTATUS_H


enum ConsultationStatus {
    AWAITING_LECTURER_CONFIRMATION,
    LECTURER_CONFIRMED,
    LECTURER_REJECTED,
    STUDENT_BOOKED,
    FREE
};


#endif //SERVER_CONSULTATIONSTATUS_H
