//
// Created by Marcin on 29.03.2019.
//

#ifndef SERVER_CONSULTATIONSTATUS_H
#define SERVER_CONSULTATIONSTATUS_H


enum ConsultationStatus {
    AWAITING_LECTURER_CONFIRMATION = 0,
    LECTURER_CONFIRMED = 1,
    LECTURER_REJECTED = 2,
    STUDENT_BOOKED = 3,
    FREE = 4
};


#endif //SERVER_CONSULTATIONSTATUS_H
